spring:
  application:
    name: api-gateway
  profiles:
      active: dev
  security:
    user:
      name: admin
      password: pwd666
  boot:
    admin:
      client:
        url: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
server:
  port: 6088

zuul:
  routes:
    doctor:                                           # 自定义， Zuul 唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /api/**                                   # 想要映射到的路径
      service-id: api-rest-doctor                     # Eureka中的serviceId
    patient:
      path: /api/**
      service-id: api-rest-patient


eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:6080/eureka/

logging:
  file: G:/mylog/api-gateway.log

---