spring:
  application:
    name: api-gateway
  profiles:
      active: dev
  security:
    user:
      name: admin
      password: pwd666
  boot:
    admin:
      client:
        url: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
server:
  port: 6088

zuul:
  prefix: /api                          # 开启全局 路径
  stripPrefix: true                     #当stripPrefix=true（http://localhost:6088/api/doctor/user/getUserInfo?id=100&token=ee -> http://localhost:6090/doctor/user/getUserInfo?id=100）
                                        #当stripPrefix=false（http://localhost:6088/api/doctor/user/getUserInfo?id=100&token=ee -> http://localhost:6090/api/doctor/user/getUserInfo?id=100）
  routes:
    doctor:                                           # 自定义， Zuul 唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /doctor/**                                # 想要映射到的路径 http://localhost:6090/doctor/user/getUserInfo?id=100 -> http://localhost:6090/user/getUserInfo?id=100
      service-id: api-rest-doctor                     # Eureka中的serviceId
    patient:
      path: /patient/**
      service-id: api-rest-patient
    auth:
      path: /auth/**
      service-id: api-rest-auth


eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:6080/eureka/

logging:
  file: G:/mylog/api-gateway.log

---