server:
  port: 8000
spring:
  application:
    name: admin-server
  profiles:
    active: dev

  security:
    user:
      name: root
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:pwd666@${eureka.instance.hostname}:6080/eureka/


logging:
  file: G:/mylog/api-admin.log
