spring:
  application:
    name: api-eureka
  profiles:
      active: dev
  security:
    user:
      name: admin
      password: pwd666
server:
  port: 6080


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
     defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
      hostname: localhost