server:
  port: 6059

spring:
  application:
    name: api-config-server
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: pwd666
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15001167619/kmc-config.git  # 配置git仓库的地址
          username: username                 # git仓库的账号
          password: password                        # git仓库的密码
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      client:
        url: http://localhost:8000


# 关闭安全管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    metadata-map:
      user.name: admin
      user.password: pwd666
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    hostname: localhost
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:6080/eureka/


