spring:
  application:
    name: api-turbine
  profiles:
      active: dev
  security:
    user:
      name: admin
      password: pwd666
  boot:
    admin:
      client:
        url: http://localhost:8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
server:
  port: 6086

turbine:
  appConfig: api-rest-doctor,api-rest-patient
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")

eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:6080/eureka/

logging:
  file: G:/mylog/api-turbine.log

---